const motivationArr = [
  "Believe",
  "Achieve",
  "Focus",
  "Discipline",
  "Consistency",
  "Growth",
  "Progress",
  "Courage",
  "Strength",
  "Confidence",
  "Dream",
  "Vision",
  "Purpose",
  "Success",
  "Hustle",
  "Grind",
  "Resilience",
  "Patience",
  "Dedication",
  "Commitment",
  "Ambition",
  "Determination",
  "Fearless",
  "Relentless",
  "Unstoppable",
  "Driven",
  "Inspired",
  "Motivated",
  "Positive",
  "Optimistic",
  "Focused",
  "Sharp",
  "Prepared",
  "Ready",
  "Energized",
  "Powerful",
  "Capable",
  "Limitless",
  "Bold",
  "Brave",
  "Strong-willed",
  "Self-belief",
  "Self-made",
  "Self-driven",
  "Mindset",
  "Excellence",
  "Greatness",
  "Potential",
  "Opportunity",
  "Momentum",
  "Clarity",
  "Action",
  "Execute",
  "Persist",
  "Never quit",
  "No excuses",
  "Stay hungry",
  "Stay focused",
  "Level up",
  "Keep going",
  "Push forward",
  "Rise up",
  "Stand tall",
  "Move ahead",
  "Take control",
  "Own it",
  "Do the work",
  "Earn it",
  "Work ethic",
  "Stay strong",
  "Stay sharp",
  "Trust yourself",
  "Be fearless",
  "Be bold",
  "Be consistent",
  "Be disciplined",
  "Be unstoppable",
  "Be relentless",
  "Chase goals",
  "Chase dreams",
  "Make it happen",
  "One step more",
  "Never settle",
  "Never doubt",
  "No limits",
  "Break barriers",
  "Prove them wrong",
  "Focus harder",
  "Stay locked in",
  "Think big",
  "Act now",
  "Start today",
  "Stay committed",
  "Win the day",
  "Daily progress",
  "Small wins",
  "Big vision",
  "Strong habits",
  "Clear goals",
  "Pure focus",
  "Mental toughness",
  "Inner strength",
  "Hard work",
  "Smart work",
  "Consistency wins",
  "Discipline wins",
  "Execution matters",
  "Progress matters",
  "Effort counts",
  "Time to grow",
  "Time to grind",
  "Rise and grind",
  "Never fold",
  "Never back down",
  "Stand your ground",
  "Take the risk",
  "Trust the process",
  "Fall forward",
  "Learn fast",
  "Adapt quickly",
  "Stay resilient",
  "Stay hungry",
  "Eyes forward",
  "Forward motion",
  "Next level",
  "Higher standard",
  "Elite mindset",
  "Winning mindset",
  "Strong focus",
  "Sharp mind",
  "Clear path",
  "Solid plan",
  "Full effort",
  "Maximum effort",
  "Keep pushing",
  "Keep improving",
  "Keep learning",
  "Stay disciplined",
  "Stay driven",
  "Stay motivated",
  "Stay consistent",
  "Rise stronger",
  "Build momentum",
  "Create value",
  "Create impact",
  "Own your future",
  "Own your path",
  "Control your mind",
  "Control your time",
  "Control your habits",
  "Work smarter",
  "Work harder",
  "Stay patient",
  "Stay persistent",
  "Never stop",
  "Never quit",
  "Never give up",
  "Make progress",
  "Take action",
  "Be intentional",
  "Be focused",
  "Be present",
  "Be powerful",
  "Be confident",
  "Be resilient",
  "Be relentless",
  "Push limits",
  "Break limits",
  "No fear",
  "No doubt",
  "No regrets",
  "No shortcuts",
  "Earn success",
  "Create success",
  "Define success",
  "Success mindset",
  "Growth mindset",
  "Winning habits",
  "Daily discipline",
  "Daily action",
  "Daily focus"
];


let main = document.querySelector('main')
let btn = document.getElementById('btn')
btn.addEventListener('click' , wordGenerator)
function wordGenerator(){
    
let div = document.createElement('div')
let word = Math.floor(Math.random() * motivationArr.length);
let x = Math.random()*100;
let y = Math.random()*100;
let c1 = Math.floor(Math.random()*256)
let c2 = Math.floor(Math.random()*256)
let c3 = Math.floor(Math.random()*256)
div.innerHTML = motivationArr[word] 

div.style.position = 'absolute'
div.style.left = x + '%'
div.style.top = y + '%'
div.style.height = '30px'
div.style.backgroundColor = `rgb(${c1} , ${c2} , ${c3})`
div.style.color = 'white'
div.style.padding = '10px'
main.appendChild(div)


}